### ISSUE TITLE
Incompatible with Electron Device OS 1.1.0

### ISSUE THREAD

**Issue by devbhullar** [rickkas7/CellularHelper#2]
The code compiles fine, but after booting the Electron gets stuck with solid white LED.

**Comment by cxcorp** [comment]
Works for me on DeviceOS 1.3.0-rc.1.

**Comment by devbhullar** [comment]
> 
> 
> Works for me on DeviceOS 1.3.0-rc.1.

Rick let me know through Particle support that I was calling CellularHelper from within the global object construction time before the cellular modem was initialized.
